package com.mahirkole.better;

public enum BetType {
    FINAL_RESULT, UNDER_OVER, DOUBLE_CHANCE, FIRST_HALF_DOUBLE_CHANCE,
    FIRST_HALF_RESULT, SECOND_HALF_RESULT, ODD_EVEN, TOTAL_GOAL,
    MUTUAL_GOAL, FIRST_HALF_15_UNDER_OVER, HAND_FINAL_RESULT,
    FIRST_AND_FINAL_RESULT, SCORE_HOME, SCORE_TIE, SCORE_AWAY
}
